---
kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: wikimediade/ansible-deploy
    pull: never # Until we publish the image
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
        - echo "$SSH_KEY" > /ansible/.ssh/id_rsa && chmod 0600 /ansible/.ssh/id_rsa
        - ansible-playbook -v -e prebuilt_source="$DRONE_WORKSPACE" -e deploy_target=test /ansible/content.yml
