---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
    - tag
    - rollback
    - promote

steps:
  - name: ci
    image: composer
    commands:
      - composer install
      - composer ci

  - name: deploy
    when:
      branch: [ test, production ]
    image: wikimediade/ansible-deploy
    pull: never # Until we publish the image on docker hub
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
        - echo "$SSH_KEY" > /ansible/.ssh/id_rsa && chmod 0600 /ansible/.ssh/id_rsa
        - ansible-playbook -v -e prebuilt_source="$DRONE_WORKSPACE" -e deploy_target="$DRONE_BRANCH" /ansible/content.yml
